# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="bureau"
CASE_SENSITIVE="true"
export UPDATE_ZSH_DAYS=13
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
HIST_STAMPS="yyyy-mm-dd"

plugins=(git colored-man colorize)

source $ZSH/oh-my-zsh.sh

# User configuration

source /etc/profile

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

# Compilation flags
export ARCHFLAGS="-arch x86_64"

export SSH_KEY_PATH="~/.ssh/dsa_id"

alias zshconfig="$EDITOR ~/.zshrc"
alias ohmyzsh="$EDITOR ~/.oh-my-zsh"

alias livempv="livestreamer --player=mpv"

export GOPATH=~/go
export PATH="$GOPATH/bin:$PATH"

export NVM_DIR="$HOME/.nvm"
[[ -s "$NVM_DIR/nvm.sh" ]] && . "$NVM_DIR/nvm.sh"  # This loads nvm

export GUILE_AUTO_COMPILE=0
export PYTHONDONTWRITEBYTECODE=1

alias dockergomi="docker ps -a | sed -e '1d; s/^\(.\{12\}\).*$/\1/'"

